name: github pages
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-python@v2
      - uses: actions/checkout@v2
      - name: install dependencies
        run: python -m pip install poetry && poetry install
        env:
          POETRY_VIRTUALENVS_CREATE: false
      - run: pip list
      - name: build docs
        run: python -m doc_note_untangler.cli . --project_name="Doc Note Untangler"
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_docs
